apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-kube-stateless-prod
spec:
  selector:
    matchLabels:
      app: cat-kube-stateless
      env: prod
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        deployedBy: deploy-to-kube
        app: cat-kube-stateless
        env: prod
    spec:
      volumes: []
      containers:
        - name: cat-kube-stateless-prod
          image: 'joycelin1600/cat-kube-stateless:prod'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5500
          resources:
            requests:
              cpu: 1m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
